# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbibackend < Formula
  desc "Install local titles into Nintendo Switch via USB"
  homepage "https://github.com/kyungw00k/dbibackend"
  version "1.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.0/dbibackend_darwin_amd64.tar.gz"
      sha256 "3bef12e9ed39f6a80027e18aaf23dd9440dcc110b779bc91806a335bbd33a29b"

      def install
        bin.install "dbibackend"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.0/dbibackend_darwin_arm64.tar.gz"
      sha256 "49c1180f63d18d9207eb6988052faf1094c6619a923a9fce8cc3e6066b3c9dc5"

      def install
        bin.install "dbibackend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.0/dbibackend_linux_amd64.tar.gz"
        sha256 "24110d3f2f3494d71cc38999f601d3b3608de5fed6c897596bf770f22d38abc7"

        def install
          bin.install "dbibackend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.0/dbibackend_linux_arm64.tar.gz"
        sha256 "4f557b879851fb790d7a849d406a084f59d68ac500539d9b9969c612283a8960"

        def install
          bin.install "dbibackend"
        end
      end
    end
  end

  test do
    assert_match "dbibackend version", shell_output("#{bin}/dbibackend --version")
  end
end
