# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbibackend < Formula
  desc "Install local titles into Nintendo Switch via USB"
  homepage "https://github.com/kyungw00k/dbibackend"
  version "1.5.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.5.1/dbibackend_darwin_amd64.tar.gz"
      sha256 "e0ecc17f9938920f2ba5e311e2910614a7ab6631bd51bbcef49acdf0e3312815"

      def install
        bin.install "dbibackend"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.5.1/dbibackend_darwin_arm64.tar.gz"
      sha256 "590c085fc58b8f9266b958ee340da0358b92ad3f9ddfb79cffb4ab7ff9fee2a5"

      def install
        bin.install "dbibackend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.5.1/dbibackend_linux_amd64.tar.gz"
        sha256 "e385a719dc22d37dc916e6bc2e83407da6b0ae6c3bcee57a991c44a9e95979bd"

        def install
          bin.install "dbibackend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.5.1/dbibackend_linux_arm64.tar.gz"
        sha256 "b9903e1f24209f4a4549b0610977010a6d3cb90a754fe91cf175de83de66e8d9"

        def install
          bin.install "dbibackend"
        end
      end
    end
  end

  test do
    assert_match "dbibackend version", shell_output("#{bin}/dbibackend --version")
  end
end
