# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbibackend < Formula
  desc "Install local titles into Nintendo Switch via USB"
  homepage "https://github.com/kyungw00k/dbibackend"
  version "1.6.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.1/dbibackend_darwin_amd64.tar.gz"
      sha256 "51d01d214dfb642b3b0fc42b241020a211968a1b4985ff95fbda3a81d028376d"

      def install
        bin.install "dbibackend"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.1/dbibackend_darwin_arm64.tar.gz"
      sha256 "d0a577ae2321ad6395b0f79c8e60e91f3065a6c26bb522cc593d3ee3aa8f13bd"

      def install
        bin.install "dbibackend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.1/dbibackend_linux_amd64.tar.gz"
        sha256 "8cdb8d306d73ea9172aa181d29f4a964acea1e11353a59776c01f89dd849c29e"

        def install
          bin.install "dbibackend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.6.1/dbibackend_linux_arm64.tar.gz"
        sha256 "dc47b465bbdb40dc6d42ddb1da156043469d620dc0391e4c93b9e57a4f06020a"

        def install
          bin.install "dbibackend"
        end
      end
    end
  end

  test do
    assert_match "dbibackend version", shell_output("#{bin}/dbibackend --version")
  end
end
