# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nxconvert < Formula
  desc "Nintendo Switch game library builder (multi-source collector, SQLite index, HTML export)"
  homepage "https://github.com/kyungw00k/nxconvert"
  version "1.9.3"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/nxconvert/releases/download/v1.9.3/nxconvert_darwin_amd64.tar.gz"
      sha256 "026afca5c60207d64b38dd62664287a125cbd33de6ba66c2427ecfea97071747"

      def install
        bin.install "nxconvert"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/nxconvert/releases/download/v1.9.3/nxconvert_darwin_arm64.tar.gz"
      sha256 "eea52304247e514d795cfe37be59fb3b9321dd8058897f7c9af12d538cc6ca61"

      def install
        bin.install "nxconvert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/nxconvert/releases/download/v1.9.3/nxconvert_linux_amd64.tar.gz"
        sha256 "02a30e963371b5922bc56e066b87c0c9784c67b3a7c6f7f96fa1a89da5c88a35"

        def install
          bin.install "nxconvert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/nxconvert/releases/download/v1.9.3/nxconvert_linux_arm64.tar.gz"
        sha256 "db5da63213bfb229c9c76fb26a8ad97b8eede92029f66bc2be726d1578df7720"

        def install
          bin.install "nxconvert"
        end
      end
    end
  end
end
